name: pyfortracc
channels:
  - conda-forge
dependencies:
  - pip=23.3.1
  - python=3.12.7
  - psutil=6.0.0
  - ipython=8.26.0
  - ipykernel=6.29.3
  - cartopy=0.23.0
  - geopandas=1.0.1
  - matplotlib=3.9.1
  - netcdf4=1.7.1
  - opencv=4.10.0
  - pyarrow=17.0.0
  - duckdb=1.1.1
  - rasterio=1.3.10
  - scikit-learn=1.5.1
  - scipy=1.14.0
  - shapelysmooth=0.2.1
  - tqdm=4.66.4
  - xarray=2024.7.0
  - pip:
      - ./