name: Docker Image CI

on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub using credentials from GitHub Secrets
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Use o secret para o nome de usuário
        password: ${{ secrets.DOCKER_PASSWORD }}  # Use o secret para a senha ou token

    - name: Build the Docker image
      run: docker build . --file tests/Dockerfile --tag pyfortracc:$(date +%s)

    - name: Tag Docker image
      run: docker tag pyfortracc:$(date +%s) fortraccproject/pyfortracc:latest

    - name: Push Docker image to Docker Hub
      run: docker push fortraccproject/pyfortracc:latest
