name: Docker Image CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub using credentials from GitHub Secrets
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      id: build_image
      run: |
        IMAGE_TAG=$(date +%s)
        docker build . --file tests/Dockerfile --tag pyfortracc:${IMAGE_TAG}
        echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV  # Define uma variável de ambiente com a tag gerada

    - name: Tag Docker image
      run: |
        docker tag pyfortracc:${{ env.IMAGE_TAG }} fortraccproject/pyfortracc:latest

    - name: Push Docker image to Docker Hub
      run: |
        docker push fortraccproject/pyfortracc:latest
